# Generated by Django 3.2.3 on 2021-06-28 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('tbtu_cdg_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id tipo usuario')),
                ('tbtu_dsc_nombre', models.CharField(max_length=255, verbose_name='Nombre tipo usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('tbus_cdg_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Usuario')),
                ('tbus_dsc_nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('tbus_dsc_apellido', models.CharField(max_length=255, verbose_name='apellido')),
                ('tbus_dsc_email', models.CharField(max_length=255, verbose_name='E-mail')),
                ('tbus_dsc_pass', models.CharField(max_length=255, verbose_name='Contraseña')),
                ('tipoUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipousuario')),
            ],
        ),
    ]
