# Generated by Django 3.2.3 on 2021-06-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tipousuario_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='atencion',
            fields=[
                ('tbat_cdg_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id atención')),
                ('tbat_dsc_titulo', models.CharField(max_length=255, verbose_name='titulo')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('tbse_cdg_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id servicio')),
                ('tbse_dsc_nombre', models.CharField(max_length=255, verbose_name='Nombre servicio')),
            ],
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='ano',
            field=models.IntegerField(default=2011, verbose_name='Año'),
            preserve_default=False,
        ),
    ]
