# Generated by Django 3.2.3 on 2021-06-29 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210628_2353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='atencion',
        ),
        migrations.DeleteModel(
            name='Servicios',
        ),
    ]
