# Generated by Django 3.2.3 on 2021-06-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_atencion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='tbat_cdg_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id atención'),
        ),
    ]
