# Generated by Django 3.2.3 on 2021-06-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_atencion_tbat_cdg_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('tbco_cdg_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id contacto')),
                ('tbco_dsc_nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('tbco_dsc_apellido', models.CharField(max_length=255, verbose_name='Apellido')),
                ('tbco_nmr_fono', models.IntegerField(verbose_name='Teléfono')),
                ('tbco_dsc_email', models.CharField(max_length=255, verbose_name='Dirección de correo electrónico')),
                ('tbco_dsc_consulta', models.CharField(max_length=300, verbose_name='¿Cómo podemos ayudarte?')),
            ],
        ),
        migrations.AlterField(
            model_name='atencion',
            name='tbat_dsc_diagnostico',
            field=models.TextField(max_length=255, verbose_name='Diagnostico'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='tbat_dsc_resena',
            field=models.TextField(max_length=255, verbose_name='Reseña'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='tbat_fch_ingreso',
            field=models.DateField(max_length=255, verbose_name='Fecha ingreso'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='tbat_img_imagena',
            field=models.ImageField(upload_to='galeria', verbose_name='Imagen 1'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='tbat_img_imagenb',
            field=models.ImageField(null=True, upload_to='galeria', verbose_name='Imagen 2'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='tbat_img_imagenc',
            field=models.ImageField(null=True, upload_to='galeria', verbose_name='Imagen 3'),
        ),
    ]
